### ISSUE TITLE
TODO 1: Deps

### ISSUE THREAD

**Issue by nathanjhood** [StoneyDSP/StoneyVCV#147]
- [x] #15 
  - [x] #21  
  - [x] #90
  - [x] #187
  - [x] #329 
  - [ ] add more SDK versions to the [vcpkg local filesystem registry](https://github.com/StoneyDSP/StoneyVCV/tree/production/dep/vcpkg/ports/rack-sdk)
  - [x] #121 
  - [x] #330
  - [ ] migrate local StoneyDSP to remote
  - [ ] migrate local vcpkg-registry to remote

**Comment by nathanjhood** [comment]
# Idea :bulb: vcpkg as a submodule with Makefile support

Easy one. Before I can truly commit to my buildsystem, I need to ensure Makefile support. To accomplish this, I need to ensure that the Makefile can find my dependencies of StoneyDSP and Catch2.

In which case, I can just add vcpkg as a submodule under `dep/vcpkg` (I already renamed the old dir in that location to `dep/vcpkg-registry` to allow this), and create the following Makefile rules:

- git submodule update init recursively
- bootstrap vcpkg if required using it's script(s) for the purpose
- set `VCPKG_ROOT` to `dep/vcpkg`
- configure CMake with `-DCMAKE_TOOLCHAIN_FILE...`, i.e., using the CMake Presets I already wrote

This seems pretty straightforward. I'm tempted to use my own fork of vcpkg, as I could in theory add my custom ports and triplets to a branch on that fork. Alternatively, I've already got a repo in this org called `vcpkg-registry` which unsurprisingly somewhat resembles the filesystem registry I created in this project - I'd need to add that repo to my vcpkg configuration JSON file...

I'm slightly more in favour of keeping the registry separate from the vcpkg repo; it will be easier to maintain, and easier to share, the registry as a vcpkg config thing... i.e., with the Rack community.
