### ISSUE TITLE
TODO 4: Design system

### ISSUE THREAD

**Issue by nathanjhood** [StoneyDSP/StoneyVCV#168]
- [x] #91
- [x] #162
- [ ] #38
  - [x] #264
  - [x] #263
  - [x] #355
  - [x] #356
  - [x] #394
- [ ] Make component library shareable
  - [x] #389
- [ ] Make design system templated and shareable
- [ ] Add to CMake package

**Comment by nathanjhood** [comment]
Thinking out loud about panels:

Fundamental LFO has a width of 9HP - here confirmed by measuring against a row of my HP1 module (pretty much what it was made to do!)

![Screenshot from 2024-12-13 04-01-08](https://github.com/user-attachments/assets/0e786aa2-c43d-4523-b9f2-7e9aa26dddd3)


I find that a bit weird though because there are 4 ports, but 9HP? We could say 0.5HP either side and we're even, but it isn't really possible to account for 0.5HP if the module were half the width of Fundamental LFO... so, it's just a "by feel" number, I guess, in Fundamental LFO's case.

I imagine it probably looks rigid and uninteresting when everything is very grid-like with equilateral placement, such as if it were 8HP.

Perhaps a good rule of thumb here - for panels generally - will be; Width = (number of ports * 2) + 1

The spare 1 just being a bit of thumb room. Pun intended.

EDIT: Hmmm... looking at it some more, the extra 1 is a helpful offset, which allows the odd-numbered "big knob" (just one of them) to sit flush in the centre of the row of even-numbered ports. Clever.

**Comment by nathanjhood** [comment]
So if an even-number N of ports fits well into a panel width of N+1... how about an odd number of ports??

If there were three ports, then I'd be inclined to make a 5HP width - so that there can still be a "centre" and just have the ports a little more spread out.

Makes me wonder if odd-numbered panel widths are a bit of a beauty spot... depending on who is beholding the eye.

**Comment by nathanjhood** [comment]
# Problem

So. Much. Boilerplate. Primarily, my module code is excessively large because:

- adding screws
- adding lines
- adding widgets
- adding framebuffers holding the widgets
- adding the framebuffers to the module widgets
- drawing panel and panel shine

## Idea

Here's something that might work...

- subclass `::rack::ModuleWidget` and add all of the above "trimmings" to it
- module widgets should subclass the above instead
- alternatively, some free functions such as `void drawPanel(const DrawArgs& args)` can probably do the same, but I'd prefer that the calling class actually owns the method/data if possible

## Bonus points

- use logic on `this->size` to determine number of screws and lines???
- drive the panel shine's color opacity value with `::rack::settings::rackBrightness` to make the panels "more dull"
- create an internal-only "DesignSystem" module as part of the plugin, which I can keep around in my Rack sessions as a "palette" for widget designs and ideas, experiments, etc, strictly to be disabled from the deployment builds

**Comment by nathanjhood** [comment]
## vague plan

- make "DesignSystem" module which is internal-only and kept out of production builds
- use this to design a set of Widget sub-classes which will be major components of the StoneyVCV design system itself
- Some widgets we need:
  - knobs of each of the 5 sizes, with underlays for panel labels and knob rings
  - in and out ports with panel labels, and underlays which indicate visually whether the port is an input or output, per VCV's Panel design suggestions
  - Lights which we like but maybe won't need until later, such as off>green>yellow>red signal meters and bipolar signal themes (blue for negative voltages, green for positive? etc)
  - trying using the screw-and-line module wrapper as a smaller sub-widget within the panels, to make parts appear to be "serviceable" from the front (I'd offer in this in certain cases if this were hardware too) 
  - figure out if making a "look-and-feel" base class which can be subclassed by all of our modules, works correctly
  - if it does, then strip the module code right down to remove all repetition and replace with this base class inheritance

In the process, I hope to also start *and* roughly finish the LFO module. This clears the way for some of the more interesting "main event" modules I have in mind, which I will broadly work on over the course of the coming months/year.

I *might* attempt to push my control modules and blank panels as a plugin to the user library meanwhile, as a placeholder for the brand name, and for the sake of investigation.

**Comment by nathanjhood** [comment]
Into the nuts and bolts and backplates now...

## Dilemma

This (port socket backplate) is a nightmare to work with:

![Screenshot from 2025-01-03 15-35-07](https://github.com/user-attachments/assets/80ffb1c2-b8c8-4803-895c-bdb803bcffb9)
![Screenshot from 2025-01-03 15-34-48](https://github.com/user-attachments/assets/4e621f10-b898-4f04-9422-802722da82ba)

Really difficult in code because the coloured backpanel (widget) is not coupled with (or a child of) the port (widget). Both the port socket, *and* the backplate are being set separately using hard-coded pixel values, which is a design-system no-no...

Really difficult in Inkscape because Inkscape...

To make matters even more complex, ports are of course circular, meaning we either work with their centred co-ordinates with some maths, or work with a leading edge, and some maths.

## Solution

Sub-class `rack::componentlibrary::ThemedPort` into a new struct which adds the themed backpanel as a `childBelow` itself....

Such a sub-class *must* be compatible with `rack::createInputCentred` and `rck::createOutputCentred` \[sic]

**Comment by nathanjhood** [comment]
> ![Screenshot from 2025-01-03 15-35-07](https://private-user-images.githubusercontent.com/97741588/399974791-80ffb1c2-b8c8-4803-895c-bdb803bcffb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MTU3MjYsIm5iZiI6MTczNTkxNTQyNiwicGF0aCI6Ii85Nzc0MTU4OC8zOTk5NzQ3OTEtODBmZmIxYzItYjhjOC00ODAzLTg5NWMtYmRiODAzYmNmZmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDE0NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzQxNTk1YjI1NDM5ZjAxNDU1NTQ5MjdhZDI4MjY0YTQxM2NjMzQzODgzMWQ3Nzk2OTIxNTdjNmVkMzIwZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MHr0TV829RnHuIemXFTCbTrwh1lfR6qBj2DCmRGfuEo) ![Screenshot from 2025-01-03 15-34-48](https://private-user-images.githubusercontent.com/97741588/399974794-4e621f10-b898-4f04-9422-802722da82ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MTU3MjYsIm5iZiI6MTczNTkxNTQyNiwicGF0aCI6Ii85Nzc0MTU4OC8zOTk5NzQ3OTQtNGU2MjFmMTAtYjg5OC00ZjA0LTk0MjItODAyNzIyZGE4MmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDE0NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGNmMTFiYjYzYjNjZTI5MzgyOWEwMjcxZjVhMDRjNzIxY2FhZGMzODJkMjYyZTM0NTJlNGE4M2VlNzU0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XuTDXXcqGt6V--KOOT6Kp-4n4mHgISgvg6iqgfAcWRY)
> 

VCA Module Widget constructor output port member initializer:

```cpp
portVcaOutput(
        ::rack::createOutputCentered<::rack::componentlibrary::ThemedPJ301MPort>(
            ::rack::math::Vec(
                size.x * 0.5F,
                // widget is 28.55155 x 39.15691
                // port is 23.7 x 23.7
                // widget.x - port.x = 4.85155 (/ 2 = 2.425775 = edge distance)
                ((39.15691F - (23.7F * 0.5F)) - 2.425775F) + (309.05634F)
            ),
            module,
            ::StoneyDSP::StoneyVCV::VCA::VCAModule::IdxOutputs::VCA_OUTPUT
        )
    )
```

VCA Module Widget `draw()` snippet for backpanel:

```cpp
void draw(const DrawArgs& args)
{
    // <SNIP>

    // draw out port box
    ::nvgBeginPath(args.vg);
    ::nvgRoundedRect(args.vg,
        /** x */(size.x * 0.5F) - (tst.x * 0.5F),
        /** y */(309.05634F),
        /** w */tst.x,
        /** h */tst.y,
        /** rx */2.83465F
    );
    ::nvgFillColor(args.vg, bgPort);
    ::nvgFill(args.vg);

    return ::rack::Widget::draw(args);
}
```

Rack internal code:

```cpp
template <class TPortWidget>
TPortWidget* createInput(math::Vec pos, engine::Module* module, int inputId) {
	TPortWidget* o = new TPortWidget;
	o->box.pos = pos;
	o->app::PortWidget::module = module;
	o->app::PortWidget::type = engine::Port::INPUT;
	o->app::PortWidget::portId = inputId;
	return o;
}


template <class TPortWidget>
TPortWidget* createInputCentered(math::Vec pos, engine::Module* module, int inputId) {
	TPortWidget* o = createInput<TPortWidget>(pos, module, inputId);
	o->box.pos = o->box.pos.minus(o->box.size.div(2));
	return o;
}
```

We can remove many of those hard-coded decimal values (xx.xxxxxF) if the sub-class idea works....

**Comment by nathanjhood** [comment]
Ok it's quite easy... just one new widget, sub-classing Rack's `ThemedPort` and over-riding `draw()`:

![Screenshot from 2025-01-03 18-01-15](https://github.com/user-attachments/assets/89f7e5f5-cc3a-4eeb-9fb6-ad222b5ab9c3)
![Screenshot from 2025-01-03 18-00-52](https://github.com/user-attachments/assets/3595d76c-4429-45a0-bba7-c30ca2f65fa5)

Now to figure out the correct placement, then add a label (optional) and some sort of logic to switch the back panel part (blue, in the above) *off* (optional).

**Comment by nathanjhood** [comment]
Big win:

![Screenshot from 2025-01-03 18-34-05](https://github.com/user-attachments/assets/d6cd88e0-9e33-4bd3-9849-5b369439867d)
![Screenshot from 2025-01-03 18-33-51](https://github.com/user-attachments/assets/e7d2ffe4-b43e-47af-b362-0310def9e94d)

**Comment by nathanjhood** [comment]
Totally worth it. I just cut the VCA code way down *and* got themed port panels:

![Screenshot from 2025-01-03 18-43-11](https://github.com/user-attachments/assets/6dbdb07a-1980-408b-9a74-9d9359c7c493)
![Screenshot from 2025-01-03 18-42-56](https://github.com/user-attachments/assets/271e72ea-be99-43bb-b4f1-6045ea2667c6)

**Comment by nathanjhood** [comment]
Labelled and themed input and output ports are live:

![Screenshot from 2025-01-04 18-17-38](https://github.com/user-attachments/assets/d914827f-2172-4540-a974-955c4320a220)

![Screenshot from 2025-01-04 18-26-08](https://github.com/user-attachments/assets/53f22be0-9738-46dd-a8e0-6411fcc8060c)

Gonna make one big, messy commit to get this into production shortly.

**Comment by nathanjhood** [comment]
I have a slider version (instead of knob) which I think I prefer for the VCA, or possibly in general... incoming.

**Comment by nathanjhood** [comment]
WIP status: working design, text labels for RoundBlackKnob:

![Screenshot from 2025-01-15 06-22-52](https://github.com/user-attachments/assets/b66acf1e-303a-42c7-b597-59a2d2e0f0af)
![Screenshot from 2025-01-15 06-22-33](https://github.com/user-attachments/assets/7a7f956f-d08b-48b7-90a4-f4f8c8091562)
![Screenshot from 2025-01-15 06-21-39](https://github.com/user-attachments/assets/b0c68092-2908-43cb-84e0-83422d0087f4)
![Screenshot from 2025-01-15 06-21-10](https://github.com/user-attachments/assets/e1ec2553-297d-472e-9802-89cf7a746ca8)

Since we can just resize the previously-known-as "opaque type" object anyway with `setSize()`, there isn't any need to make one panel for each size of knob; just access the element in the Vector as needed.

Here, I used the exact same Knob Panel struct, simply swapped `RoundSmallBlackKnob` for `RoundHugeBlackKnob`, and passed the `gainKnob` widget instance's size to the Knob Panel's `setSize()`, and the text adjusted accordingly: 

![Screenshot from 2025-01-15 07-29-02](https://github.com/user-attachments/assets/ddb92f2a-3b37-4bee-994c-4e7712d36a2e)
![Screenshot from 2025-01-15 07-28-36](https://github.com/user-attachments/assets/06498e20-9274-490b-ba49-d45f8a9a1afd)
![Screenshot from 2025-01-15 07-27-51](https://github.com/user-attachments/assets/7522e148-15f9-4b0e-a3fc-c1104357d55d)
![Screenshot from 2025-01-15 07-27-13](https://github.com/user-attachments/assets/b9723a25-4536-4f0a-b037-a0705bfca818)

So, the cropped outer ring should be able to work the same!

Still to come: add the outer ring, including an (enum?) accessor to specify whether the Knob is unipolar, or bipolar.

Extra points if we can deduce the crop angle of the outer ring using the `minValue` and `maxValue` members...

WIP: Added a cutaway with the (one-armed) scissor:

![Screenshot from 2025-01-15 23-28-21](https://github.com/user-attachments/assets/9e40395c-97cf-46b6-a744-29655c0f7f65)
![Screenshot from 2025-01-15 23-28-07](https://github.com/user-attachments/assets/91cbda26-a7e9-49e1-b36b-783c32eaa28a)
![Screenshot from 2025-01-15 23-26-49](https://github.com/user-attachments/assets/fd1eccca-e9f7-4f69-a3b5-e1c935bd7bac)
![Screenshot from 2025-01-15 23-26-33](https://github.com/user-attachments/assets/daad2ec5-41b4-42d0-89a8-d670b5cefc51)

I believe the slightly ugly flat-top of the clipping could be improved, by replacing this scissor method - whereby I'm simply cropping the viewbox by some constant amount(s) - with another hollow circle, moved away from the centre towards the clipping region.

Nonetheless, I've sure seen (and done) much worse than this attempt. In some sense, it's good enough to pass.

WIP update: using `nvgArc` with rounded linecap for the win:

![Image](https://github.com/user-attachments/assets/40f5a336-6f75-4758-bf8f-9bd6272674ee)
![Image](https://github.com/user-attachments/assets/25e78645-975a-4189-8725-3e0e9124593a)
![Image](https://github.com/user-attachments/assets/1bc743b5-06e4-4a6c-9dd1-d3f55e5c800f)
![Image](https://github.com/user-attachments/assets/70680de7-7a1f-42ed-942d-e18475de9b1e)

The values of `nvgArc` are *exactly* the values taken from the knob widget's min and max, and it's quite simple overall.

So, to prove a point... let's try throwing some weird min/max values and different knob sizes - no other changes - while cleaning up the debris of unused code I've got locally (some of which I'll probably put in the StoneyDSP lib as it's useful nonetheless, if not here).

EDIT: update 

> So, to prove a point...

...I:

- reduced the knob min and max values arbitrarily
- changed Widget variation from `Huge` to `Small`

Result:

![Image](https://github.com/user-attachments/assets/9f070499-d09e-475b-a26d-e4cbb6917309)
![Image](https://github.com/user-attachments/assets/bc934e07-3218-4e24-b855-4f906a3b2bde)

The knob ring is perfectly tracking the parent widget's range! 🆒 

The margin, or "leading" seems a bit "wrong" here, too much of it for the smaller widget size... but since that variable can be easily set externally, it's no show-stopper; I've already accomplished more here than I actually expected to.

EDIT: Mission accomplished:

Close-up showing rounded linecaps and corners, and nice even spacings:

![Screenshot from 2025-01-18 06-44-13](https://github.com/user-attachments/assets/bda63283-fbbc-4b3a-90db-55da55d62d1a)
![Screenshot from 2025-01-18 06-43-59](https://github.com/user-attachments/assets/774efd8d-d449-46e6-9e7d-4e8177dbeca9)
![Screenshot from 2025-01-18 06-43-43](https://github.com/user-attachments/assets/3d1b4ca4-dd68-40cd-b682-52255acbec4c)
![Screenshot from 2025-01-18 06-43-25](https://github.com/user-attachments/assets/94ce0c6c-d3ab-4ffb-b780-8c4368206b3a)
![Screenshot from 2025-01-18 06-42-23](https://github.com/user-attachments/assets/b5e38223-ed0a-47a8-8bbe-139b85d59250)
![Screenshot from 2025-01-18 06-42-07](https://github.com/user-attachments/assets/d39ab9ba-78ad-417e-9147-794e10fc5f4c)

(VCA module still in draft mode here):

![Screenshot from 2025-01-18 07-16-16](https://github.com/user-attachments/assets/fd4cfd8f-5264-422d-9e44-520583e801d7)
![Screenshot from 2025-01-18 07-15-58](https://github.com/user-attachments/assets/f3dff5a3-2626-436a-ad5c-c3b4610af52c)

:+1:

**Comment by nathanjhood** [comment]
Latest: I was able to draught this LFO panel up very quickly (comparatively speaking) within nanoVG, using the new design system and component library Widgets:

![Image](https://github.com/user-attachments/assets/8d15ecf9-7a0e-4737-9e09-fa3ef86b0c9b)
![Image](https://github.com/user-attachments/assets/fba805e3-63a0-4cf2-89d1-cf2bf6f1adfb)

Plenty missing, and some obvious thoughts straight off the bat (port spacing?) but lots of great things "just worked":

- lines and (themed) screws automatically placed and drawn
- knob ring from min to max values of the knob's range
- knob is labelled and the text is not obfuscated by the size of the knob
- ports are clearly outputs thanks to the ThemedPortPanelWidget
- port panels merge nicely when close enough (though too close here, tbh)
- ports are labelled
- all the above responds to light/dark theme changes and already uses the global theme (text and BG colors, font, lighting/gradient...)
- one framebuffer holding most of the above

There are a couple more smells under the hood, particularly in Module and ModuleWidget constructor code...

We might be too far in to the LFO already to fish those things out effectively while developing this module; I'll probably sprint to get a few more of this module's features in place before anything else.

**Comment by nathanjhood** [comment]
Interesting - and, expected - challenge with the panel spacing:

![Image](https://github.com/user-attachments/assets/ae516df6-173c-4bfc-9410-68d2b550e1b6)
![Image](https://github.com/user-attachments/assets/aaa40433-4afb-41aa-809f-addc9fa66515)
![Image](https://github.com/user-attachments/assets/8cd989db-2ec5-4c02-ac94-3af15c600aed)
![Image](https://github.com/user-attachments/assets/6a9e1764-62f9-47b3-8d7d-444da58c3229)

I don't like the port panels being flush against the panel bounds (inner lines) - I think in a hardware scenario, those areas would be a little bit flimsy without the right care, and hence I'm using those inner lines to tell myself what my "safe margin" is, at least according to what's in my head about hardware panels.

In this case, I'll probably reduce the gap just enough and see if I can condense the port panels into one, without squishing up the thumb room for handling cables. If necessary, I'll add some sort of variable to set corner types on the port panel widgets....

**Comment by nathanjhood** [comment]
> There are a couple more smells under the hood, particularly in Module and ModuleWidget constructor code...

I rooted this one out.

In summary; since the `std::vector`s various widget types are specified some levels of inheritance away from the final module, I had overlooked something which was causing runtime exceptions whenever I tried to access elements at position 0 on any of these arrays.

The problem *was*, that I have specified an in-class initialiser to a null-ish value on each of these vectors. This null-ish value at position 0 was making its' way all the way to the instantiated module constructor, where I was mistakenly thinking I was reserving and emplacing new elements into an *empty* vector, having overlooked that this null-ish value was already in there... d'oh!

Just adding `vec.clear()` before the emplacing of elements allows us to massively reduce all of that smelly constructor code down into proper, normal/sane iterable semantics instead. Which was of course the original idea - i Just got waylaid by tat unexpected runtime exception on element position 0 for a minute....

There are still some cases where specific element access is desired - setting labels and other ephemeral, unique options - and that is completely reasonable.

I'll update the VCA module in due course, and the blank panels eventually (if at all).

**Comment by nathanjhood** [comment]
# What I really want to do is...

(pseudo-code)

- Add a data member to the `<name>Widget` structs' parent class, which is a reference to a `::rack::ModuleWidget`
- when constructing/initializing `<name>Widget`, pass the owning `::rack::ModuleWidget` to the constructor by reference
- use this live reference to the owning struct, to organize all the panel layout within the `<name>Widget` constuctor
- for example, all the panels for ports and knobs could all be done directly in one place, rather than two

The blocker:

- need a friend function for creating the `<name>Widget` which accepts the `::rack::ModuleWidget` by reference, and does not interfere with any existing functions or implementations (probably should be something like `createPanelWidget(const ModuleWidget &mw)`)
- in our ModuleWidget constructors, replace the generic `createWidget<{name}Widget>` with the above
- Rack already has `createPanel` but this does a bunch of extra stuff - some we deffo want, some we don't need - and accepts only an SVG via shared pointer
- I'm also considering sub-classing `::rack::ModuleWidget` as part of the design system... and still pondering how that might affect my needs stated above
